version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: innova
      MONGO_INITDB_ROOT_PASSWORD: innova2019
    volumes:
      - './data:/data/db'

  backend: 
    image: inoova_backend:v1
    restart: always
    ports: 
      - "3000:3000"

  

