version: "3.1"
volumes:
  db:

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: innova
      MONGO_INITDB_ROOT_PASSWORD: innova2019
    volumes:
      - "./data:/data/db"

  redis:
    image: "redis:alpine"

  backend:
    build: ./backend
    restart: always
    environment: 
      - MONGO_USERNAME=innova
      - MONGO_PASSWORD=innova2019
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=smartphr
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  nextcloud_db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8081:80
    links:
      - nextcloud_db
    volumes:
      - /root/smartphr/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db

  frontend:
    image: smartphr_frontend:v1
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mongo
      - backend

