name: Frontend

# on: workflow_dispatch

#  release:
#    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
#    types: [published, created, edited]
#    paths-ignore:
#      - 'docs/**'
#      - 'scripts/**'
#      - 'certificate/**'
#    paths:
#      - '!README.md'
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/smartiphr/
          file: ./frontend/smartiphr/Dockerfile
          push: true
          tags: smart-iphr.innovaware.it:5000/frontend:latest
